from .crm_lead import CrmLead
from .res_partner import ResPartner
from .res_users import ResUser
from .base import Table
from .res_partner_res_partner_category_rel import ResPartnerResPartnerCategoryRel
from .crm_team import CrmTeam
from .users_crm_team import UsersCrmTeam
from .base_master_data import BaseMasterData
from .utm_medium import UtmMedium
from .crm_tag_rel import CrmTagRel
from .crm_lead_track_level_up import CrmLeadTrackLevelUp
from .res_groups import ResGroups
from .res_groups_users_rel import ResGroupsUsersRel
from .res_partner_category import ResPartnerCategory
from .ir_module_category import IrModuleCategory
from .crm_stage import CrmStage
from .res_users_role import ResUsersRole
from .res_users_role_line import ResUsersRoleLine
from .res_company_users_rel import ResCompanyUsersRel
from .res_groups_implied import ResGroupsImplied
